name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # את יכולה לבחור את גרסת הפייתון המתאימה לך

    - name: Clean environment
      run: |
        sudo apt-get clean
        sudo rm -rf /opt/hostedtoolcache/Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dash==2.0.0 plotly==5.0.0 pytest==6.0.0 pandas==1.3.0

    - name: Run tests
      run: |
        pytest
